### ISSUE TITLE
Cutting Board Server & Client Crash

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/some-assembly-required#1]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Some Assembly Required v1.1.0`
[`Pokecube AIO v3.4.1`](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)
[`Fariy Lights v4.0.3`](https://www.curseforge.com/minecraft/mc-mods/fairy-lights)

When I tried to place a cutting board, the server crashed with Pokecube AIO, while at the same time, the client crashed with Fairy Lights...
[Client Crash Report ](https://gist.github.com/WenXin20/e9f305551a32e3b13d62263832f85e8d)
[Server Crash Report](https://gist.github.com/WenXin20/765103acda13a7d257b8a13ff108f06e)

**Comment by ochotonida** [comment]
Thanks for the report, I've uploaded a patch

**Comment by WenXin20** [comment]
Thanks!
