### ISSUE TITLE
Farmer Delight's advancement

### ISSUE THREAD

**Issue by xtrial** [ochotonida/some-assembly-required#11]
Can you include SAR's cutting board to FD cutting board advancement trigger? 
Background: I want to unify the mods, so i disabled FD cutting board, but it's impossible to get FD's cutting board advancement without using FD's.

:)

**Comment by ochotonida** [comment]
I don't think there's a straightforward way to fix this unfortunately. I'll keep this open in case I figure something out

**Comment by ochotonida** [comment]
This mod no longer has it's own cutting board in 1.18+, it is now a Farmer's Delight addon. I'm going to close this issue, as the 1.16 version of this mod will no longer receive any content updates.
