### ISSUE TITLE
[Request] Whitelist of non-food items

### ISSUE THREAD

**Issue by DarkYuan** [ochotonida/some-assembly-required#14]
**Description**
Being able to put certain configurable items in a sandwich that aren't directly edible, such as sugar, or salt from other mods

**Problem or Reasoning**
Mainly this would be for aesthetic reasons, but might also add something to the sandwich like mayonnaise does. I wanna put pepper on my BLT's!

**How it will work**
A whitelist in the config would determine what items should be used in sandwiches regardless of edibility. These could either just do nothing, or perhaps give a small boost to saturation of the finished product.

**Comment by ochotonida** [comment]
This is possible in the 1.18 version using data packs. I still need to create a guide to explain the json format, but I'm going to go ahead and close this issue as the 1.16 version of this mod will no longer receive any content updates.
