### ISSUE TITLE
Multiplayer Crash on block destroy

### ISSUE THREAD

**Issue by Khazoda** [ochotonida/some-assembly-required#2]
When breaking a placed sandwich, or breaking the sandwich assembly table, any other players on a multiplayer server within a certain range crash to desktop.

[crash-2020-12-26_17.34.09-client.txt](https://github.com/ochotonida/some-assembly-required/files/5743596/crash-2020-12-26_17.34.09-client.txt)

**Comment by Ibirtem** [comment]
same problem

**Comment by ochotonida** [comment]
The problem should be fixed in the latest patch
