### ISSUE TITLE
[Enhancement] Any items on sandwich

### ISSUE THREAD

**Issue by bearsjunior** [ochotonida/some-assembly-required#23]
It would be cool if there was a config to allow you to put any items on sandwiches.

**Comment by ochotonida** [comment]
This is actually already possible, although it does require a data pack, and you will need to create a separate file for each item you want to be able to put on a sandwich. I've added a brief explanation of the JSON format on the README.

I won't be adding a config option to do this for now, as it's already possible. I do understand data packs aren't for everyone though, so if it's a common request I might reconsider in the future.
