### ISSUE TITLE
[1.18.1] Crash when Diet tries to render nutrition tooltips on Sandwiches with any Potion added

### ISSUE THREAD

**Issue by Prunoideae** [ochotonida/some-assembly-required#24]
Crash report:
[crash-2022-03-12_13.19.18-client.txt](https://github.com/ochotonida/some-assembly-required/files/8237668/crash-2022-03-12_13.19.18-client.txt)

starts at
https://github.com/ochotonida/some-assembly-required/blob/fd088360f82ef587d61705d9ecbf3d37e0d5ae0c/src/main/java/someassemblyrequired/integration/diet/DietCompat.java#L34

where
https://github.com/ochotonida/some-assembly-required/blob/fd088360f82ef587d61705d9ecbf3d37e0d5ae0c/src/main/java/someassemblyrequired/common/item/sandwich/SandwichItemHandler.java#L67-L73

but
https://github.com/ochotonida/some-assembly-required/blob/fd088360f82ef587d61705d9ecbf3d37e0d5ae0c/src/main/java/someassemblyrequired/common/ingredient/Ingredients.java#L51-L53
https://github.com/ochotonida/some-assembly-required/blob/fd088360f82ef587d61705d9ecbf3d37e0d5ae0c/src/main/java/someassemblyrequired/common/ingredient/PotionProperties.java#L27-L29

**Comment by ochotonida** [comment]
Thanks for the detailed report! Diet didn't have a release for 1.18 yet when I implemented compatibility, that's why I forgot to properly test it. I've uploaded a patch that fixes the issue. (It seems there's some issues with curseforge at the moment though, it might take some time to be approved)
