### ISSUE TITLE
[1.18.1] Recipe Overlaps make certain automation impossable

### ISSUE THREAD

**Issue by Shibva** [ochotonida/some-assembly-required#25]
I was experimenting around and found that the sandwich system seems to break other recipes for some unknown reasons

for example, anything using the spout gets turned into a sandwich for some reason (bucket fluid sandwich)

please look into this, its kind of annoying

Repoducing this should be as simple as having the spout trying to fill a fluid up in an item that should NOT be a sandwich

**Comment by ochotonida** [comment]
Thanks for the report. I've uploaded a patch that should fix the issue
