### ISSUE TITLE
Create Error?

### ISSUE THREAD

**Issue by Gelox1209** [ochotonida/some-assembly-required#30]
An odd error pops up when using latest forge version for 1.18.2, and latest version for both create and sar(some assembly required).

The error: Exception caught during firing event: BUILDERS_TEA

The entire log:
[8-15-7.log](https://github.com/ochotonida/some-assembly-required/files/9340601/8-15-7.log)
.

**Comment by ochotonida** [comment]
Fixed in version 2.0.8
