### ISSUE TITLE
The item lays vertically on the cutting board in the newer version of forge

### ISSUE THREAD

**Issue by gousisme** [ochotonida/some-assembly-required#35]
I don't have much time to check since what version does this but it works fine in 43.1.43 and looks vertically in 43.1.57
here's the image of the bug
![image](https://user-images.githubusercontent.com/77152530/206264827-9d9cb34b-218f-41f2-9bb1-6b9266167e36.png)

**Comment by ochotonida** [comment]
This is not an issue with Some Assembly Required, the cutting board is added by Farmer's Delight. https://github.com/vectorwing/FarmersDelight/issues/594
