### ISSUE TITLE
Crash with Create spout recipes

### ISSUE THREAD

**Issue by moon-st0ne** [ochotonida/some-assembly-required#36]
On latest version of Create, FD, and SAR. Was playing on a server with a friend. Added a half-complete sandwich to a spout with chocolate and the server crashed until we relaunched it without this mod loaded.

[latest.log](https://github.com/ochotonida/some-assembly-required/files/10182387/latest.log)

**Comment by Ellisthion** [comment]
I also ran into this. I believe this occurs when the fluid is not explicitly supported by the mod. Potions always work, as do fluids that have a config for them (eg honey, milk), but fluid chocolate doesn't have a config by default and the server crashes.

**Comment by ochotonida** [comment]
Sorry for the long wait - should be fixed in version 1.19.2-3.0.1
