### ISSUE TITLE
[Suggestion] JEI Integration

### ISSUE THREAD

**Issue by ocram9** [ochotonida/some-assembly-required#4]
I'm not sure if the title is worded correctly but what I mean is adding the toaster to the left of the JEI interface when a recipe is selected that requires the toaster (for example). It's a small thing but it saves a bit of time when you want to know a crafting recipe.

![Screenshot_19](https://user-images.githubusercontent.com/49008532/103304146-1ce69780-4a08-11eb-8340-57887d0a3240.png)

Example: when selecting a recipe, you'll see all the, in this case, crafting table variants on the left.

![Screenshot_20](https://user-images.githubusercontent.com/49008532/103304329-a5653800-4a08-11eb-88a7-685fcf9a447c.png)

The recipes from this mod don't have that.

**Comment by ochotonida** [comment]
Thanks for the report, I had some trouble figuring out how to properly add JEI integration since the wiki is a bit out of date, and it seems like I overlooked something. I've uploaded a patch that fixes the issue
