### ISSUE TITLE
[Suggestion]When the stacking of sandwiches meets certain conditions, specific food can be output.

### ISSUE THREAD

**Issue by SolarMoonQAQ** [ochotonida/some-assembly-required#42]
Just a whim, can a new 'sandwich recipes' be created in the data package so that a specific food can be stacked by modifying the data package?For example, when I stack in the order of bread slices, cooked bacon, cabbage, tomatoes, and bread slices on the Sandwich Assembly Table, I can ultimately output a bacon sandwich of farmer's delight.

**Comment by ochotonida** [comment]
This isn't possible at the moment, but you could probably achieve something similar by allowing players to convert sandwiches to the item you want with a crafting recipe. Forge adds NBT ingredients which you can use to match against specific sandwiches: https://docs.minecraftforge.net/en/latest/resources/server/recipes/ingredients/. `StrictNBTIngredient` should work for this purpose. You can use these in any recipe type that accepts items, even modded ones. I don't remember exactly what the nbt of sandwiches looks like, but you can probably figure it out yourself by sticking one in a chest and using the `/data` command.

While the solution I described adds an extra step, adding a system specifically for this to the mod would be a bit too much work for what it's worth.

**Comment by SolarMoonQAQ** [comment]
This is a genius like alternative solution, thank you for your reply!
