### ISSUE TITLE
List of missing/incomplete translation keys

### ISSUE THREAD

**Issue by ochotonida** [ochotonida/some-assembly-required#7]
This issue is here to provide an overview of missing translation keys for people that want to contribute.
I'll keep this comment updated when new versions are released.

Currently:
`de_de` is up to date.
`pt_br` is missing the following entries from update 1.16.5-1.3.0:
- advancements:
  - all titles & descriptions
- blocks:
  - lettuce (crop)
  - tomatoes (crop)
- items:
  - tomato, tomato slices/seeds
  - ketchup
  - lettuce head/leaf/seeds
- sandwich item names:
  - BLT
  - most of the other sandwich names could use another look as well, I changed how sandwich names are generated and had to extrapolate a bit
- ingredient names: (these are the names of items as they appear in the display name of a sandwich)
  - everything except toast
- spread types:
  - mayonnaise
- JEI descriptions:
  - tomato, tomato slices, ketchup
  - lettuce head/leaf
  - a lot of these have changed since I've moved them from the tooltip to JEI, could use a check if these are still accurate

**Comment by Geolykt** [comment]
K, I'll try to update them (de_de) in the coming days

**Comment by ochotonida** [comment]
Gonna close this since all translations are updated, I'll probably open a new issue once it's needed instead of reusing this one so things don't get too cluttered
