### ISSUE TITLE
IllegalStateException error on world creation / load with Immersive Engineering 

### ISSUE THREAD

**Issue by egshels** [ochotonida/some-assembly-required#8]
Generating or loading a world gives this error ever since installing this mod
![image](https://user-images.githubusercontent.com/31183838/104829903-a1c61380-5846-11eb-9936-b0d9297e6aec.png)
This only happens with Immersive Engineering 
https://pastebin.com/Kn0cnh5T
I have no actual datapacks installed

**Comment by ochotonida** [comment]
I've uploaded a patch that should fix the issue
